# this file is managed by dry-rb/devtools project

name: release

on:
  repository_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch' && github.event.action == 'release'
    env:
      GITHUB_LOGIN: dry-bot
      GITHUB_TOKEN: ${{secrets.GH_PAT}}
      GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}
      RELEASE_CREATOR: ${{github.event.client_payload.tag_creator}}
      RELEASE_TAG: ${{github.event.client_payload.tag}}
      RELEASE_REPO: ${{github.event.client_payload.repo}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.event.client_payload.repo}}
          ref: refs/tags/${{github.event.client_payload.tag}}
      - name: Set up Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.6
      - name: Set up gem credentials
        run: |
          mkdir -p ~/.gem
          echo ":rubygems_api_key: $GEM_HOST_API_KEY" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
      - name: Install dependencies
        run: gem install gem-release ossy
      - name: Publish ${{github.event.client_payload.repo}} ${{github.event.client_payload.tag}} to Rubygems
        run: |
          name=$(ossy gh t $RELEASE_REPO $RELEASE_TAG)
          login=$(ossy gh om "$name" dry-rb)

          if [[ $login == $RELEASE_CREATOR ]]; then
            ossy gh m $login dry-rb core --verify=true && gem release
          else
            echo "Tagger is different than release creator: $login != $RELEASE_CREATOR"
          fi
