on:
  push:
    paths:
      - .github/workflows/trigger_sync_configs.yml
      - shared/**
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6.x"
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --without benchmarks sql
      - name: Symlink ossy
        run: ln -sf "$(bundle show ossy)/bin/ossy" bin/ossy
      - name: Trigger config synchronization in dry-rb repositories
        env:
          GITHUB_LOGIN: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: for name in `cat projects`; do bin/ossy gh w dry-rb/$name sync_configs
